export enum Action{
    NOPROMOTION = "NOPROMOTION",
    WHITEPROMOTION = "PROMOTION:WHITE",
    BLACKPROMOTION = "PROMOTION:BLACK",
    KILLED = "KILLED",
    MOVE = "MOVE",
    KINGMOVE = "KINGMOVE",
    KINGLOSE = "KINGLOSE",
    KINGSAFE = "KINGSAFE"
}