export enum Action{
    NOPROMOTION = "NOPROMOTION",
    WHITEPROMOTION = "WHITEPROMOTION",
    BLACKPROMOTION = "BLACKPROMOTION",
    KILLED = "KILLED",
    MOVE = "MOVE",
    KINGMOVE = "KINGMOVE",
    KINGLOSE = "KINGLOSE",
    KINGSAFE = "KINGSAFE"
}