name: Node.js CI

on:
  push:
    branches: "*"
    tags: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "chess-front/package-lock.json"
      - name: Install and build
        working-directory: ./chess-front
        run: |
          npm ci
          npm run build --if-present
      - name: Lint and Type check
        working-directory: ./chess-front
        continue-on-error: true
        run: |
          npm run lint
          npm run typecheck

  deploy:
    if: github.ref_type == 'tag'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: bankfliptech/deploy-to-render@v1
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          deployHookURL: ${{ secrets.STATIC_SITE }}
          wait-for-deployment: true