name: Node.js CI

on:
  push:
    tags: "*"
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "chess-back/package-lock.json"
      - name: Install and build
        working-directory: ./chess-back
        run: |
          npm ci
          npm run generate
          npm run build --if-present
      - name: Lint and Type check
        working-directory: ./chess-back
        continue-on-error: true
        run: |
          npm run lint
          npm run typecheck
      - name: Build Docker Image (Dev or Prod)
        working-directory: ./chess-back
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            docker build -t ${{ vars.USERNAME }}/chess-back:dev .
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            docker build -t ${{ vars.USERNAME }}/chess-back:prod .
          fi

      - name: Log in to Docker Hub
        run: echo "${{ secrets.TOKEN }}" | docker login -u "${{ vars.USERNAME }}" --password-stdin
      
      - name: Push Docker Image (Dev or Prod)
        working-directory: ./chess-back
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            docker tag ${{ vars.USERNAME }}/chess-back:dev ${{ vars.USERNAME }}/chess-back:dev
            docker push ${{ vars.USERNAME }}/chess-back:dev
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            docker tag ${{ vars.USERNAME }}/chess-back:prod ${{ vars.USERNAME }}/chess-back:prod
            docker push ${{ vars.USERNAME }}/chess-back:prod
          fi

  deploy_dev:
    if: github.ref == 'refs/heads/dev'
    needs: build
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Deploy to Render (Dev)
        uses: gh-actions-workflows/deploy-docker-render@v1.1
        with:
          deploy-hook: ${{ secrets.WEB_SERVICE_DEV }}
          image-url: ${{ vars.USERNAME }}/chess-back:dev
          render-api-key: ${{ secrets.RENDER_API_KEY_DEV }}
          wait-for-deployment: true

  deploy_prod:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Deploy to Render (Prod)
        uses: gh-actions-workflows/deploy-docker-render@v1.1
        with:
          deploy-hook: ${{ secrets.WEB_SERVICE_PROD }}
          image-url: ${{ vars.USERNAME }}/chess-back:prod
          render-api-key: ${{ secrets.RENDER_API_KEY_PROD }}
          wait-for-deployment: true
