name: Node.js CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "chess-back/package-lock.json"
      - name: Install and build
        working-directory: ./chess-back
        run: |
          npm ci
          npm run generate
          npm run build --if-present
      - name: Lint and Type check
        working-directory: ./chess-back
        continue-on-error: true
        run: |
          npm run lint
          npm run typecheck
      - name: Build Docker Image
        working-directory: ./chess-back
        run: |
          docker build -t chess-backend:latest .
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.TOKEN }}" | docker login -u "${{ secrets.USERNAME }}" --password-stdin
      
      - name: Push Docker Image
        working-directory: ./chess-back
        run: |
          docker tag ${{ secrets.USERNAME }}/chess-back:latest ${{ secrets.USERNAME }}/chess-back:latest
          docker push ${{ secrets.USERNAME }}/chess-back:latest    